package com.gjjx.carvideo.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gjjx.carvideo.db.TBSubject;
import com.gjjx.carvideo.db.TBCourse;
import com.gjjx.carvideo.db.TBClass;

import com.gjjx.carvideo.db.TBSubjectDao;
import com.gjjx.carvideo.db.TBCourseDao;
import com.gjjx.carvideo.db.TBClassDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tBSubjectDaoConfig;
    private final DaoConfig tBCourseDaoConfig;
    private final DaoConfig tBClassDaoConfig;

    private final TBSubjectDao tBSubjectDao;
    private final TBCourseDao tBCourseDao;
    private final TBClassDao tBClassDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tBSubjectDaoConfig = daoConfigMap.get(TBSubjectDao.class).clone();
        tBSubjectDaoConfig.initIdentityScope(type);

        tBCourseDaoConfig = daoConfigMap.get(TBCourseDao.class).clone();
        tBCourseDaoConfig.initIdentityScope(type);

        tBClassDaoConfig = daoConfigMap.get(TBClassDao.class).clone();
        tBClassDaoConfig.initIdentityScope(type);

        tBSubjectDao = new TBSubjectDao(tBSubjectDaoConfig, this);
        tBCourseDao = new TBCourseDao(tBCourseDaoConfig, this);
        tBClassDao = new TBClassDao(tBClassDaoConfig, this);

        registerDao(TBSubject.class, tBSubjectDao);
        registerDao(TBCourse.class, tBCourseDao);
        registerDao(TBClass.class, tBClassDao);
    }
    
    public void clear() {
        tBSubjectDaoConfig.getIdentityScope().clear();
        tBCourseDaoConfig.getIdentityScope().clear();
        tBClassDaoConfig.getIdentityScope().clear();
    }

    public TBSubjectDao getTBSubjectDao() {
        return tBSubjectDao;
    }

    public TBCourseDao getTBCourseDao() {
        return tBCourseDao;
    }

    public TBClassDao getTBClassDao() {
        return tBClassDao;
    }

}
