package com.gjjx.carvideo.db;

import com.gjjx.carvideo.db.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TBCOURSE".
 */
public class TBCourse {

    private Long id;
    private long sub_id;
    private String name;
    private String summary;
    private String url;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TBCourseDao myDao;

    private TBSubject tBSubject;
    private Long tBSubject__resolvedKey;


    public TBCourse() {
    }

    public TBCourse(Long id) {
        this.id = id;
    }

    public TBCourse(Long id, long sub_id, String name, String summary, String url) {
        this.id = id;
        this.sub_id = sub_id;
        this.name = name;
        this.summary = summary;
        this.url = url;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTBCourseDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getSub_id() {
        return sub_id;
    }

    public void setSub_id(long sub_id) {
        this.sub_id = sub_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    /** To-one relationship, resolved on first access. */
    public TBSubject getTBSubject() {
        long __key = this.sub_id;
        if (tBSubject__resolvedKey == null || !tBSubject__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TBSubjectDao targetDao = daoSession.getTBSubjectDao();
            TBSubject tBSubjectNew = targetDao.load(__key);
            synchronized (this) {
                tBSubject = tBSubjectNew;
            	tBSubject__resolvedKey = __key;
            }
        }
        return tBSubject;
    }

    public void setTBSubject(TBSubject tBSubject) {
        if (tBSubject == null) {
            throw new DaoException("To-one property 'sub_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.tBSubject = tBSubject;
            sub_id = tBSubject.getId();
            tBSubject__resolvedKey = sub_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
